sudo: false

language: python

python:
  - 3.7.6

install:
  - pip install -r requirements.txt

script:
  - python run.py

env:
  global:
    - SQLALCHEMY_DATABASE_URI='postgres://qaira:$3cq4IR4@qairamap-db-dev.c6xdvtbzawt6.us-east-1.rds.amazonaws.com:5432/qairamap_db'
    - SECRET_KEY=my_precious