language: python
dist: bionic
python:
- 3.7.6
cache: pip
before_cache:
- rm -vrf $HOME/.cache/pip/{http,log}
install:
- rm -vrf $HOME/.cache/pip/{http,log}
- pip install -r requirements.txt
- pip install coverage==4.5.4
script:
- pytest -v --cov=project/main/
- coverage run -m pytest project/test/
after_success: 
- coverage report --omit '/home/travis/virtualenv/python3.7.6/lib/python3.7/site-packages/*'
- coveralls
env:
  global:
    - SQLALCHEMY_DATABASE_URI='postgres://qaira:$3cq4IR4@qairamap-db-dev.c6xdvtbzawt6.us-east-1.rds.amazonaws.com:5432/qairamap_db'
    - SECRET_KEY=my_precious
notifications:
  email:
    recipients:
    - l.montalvo@qairadrones.com
