language: python
dist: bionic
python:
- 3.7.6
cache: pip
install:
- pip install -r requirements.txt
- pip install coverage==4.5.4
- pip install python-coveralls
- pip install pytest pytest-cov
script:
- pytest -v
- coverage run -m pytest project/test/
after_success: coveralls
env:
  global:
    - SQLALCHEMY_DATABASE_URI_OPEN = $DB_ACCESS
notifications:
  email:
    recipients:
    - l.montalvo@qairadrones.com